repeat_experiments:                 10
#ctx:                                'remaining_crop_models'
#ctx:                                'test_robust_stats_moteStrain'
ctx:                                'marabou_robust_repeat'
mode:                               ['test']
multiple_models:                    './models/trained_models/autoencoder_sinecurve_denoising'
#multiple_models:                    './models/trained_models/autoencoder_crop_diff_ds'
#multiple_models:                    Null
dataset:                            'melbournePedestrian'
#algorithm:                          './models/trained_models/autoencoder_mnist_784_150_10'
#algorithm:                          './models/trained_models/autoencoder_mnist'
#algorithm:                          './models/autoencoder_float_test'
#algorithm:                          './models/autoencoder_mnist_dropout'
#algorithm:                          './models/autoencoder_predMain_airTemp'
algorithm:                          './models/trained_models/autoencoder'
#algorithm:                          './models/trained_models/autoencoder_gaussianClouds_100_50_30_border_fct_dist'
#algorithm:                          './models/trained_models/autoencoder_test_nan'
#algorithm:                          'autoencoder'
evaluations:                        [
    #'parallelQualplots',
    #'downstream_kmeans',
    #'downstream_naiveBayes',
    #'downstream_knn',
    #'downstream_rf',
    #'tsne_latent',
    #'linSubfctBarplots',
    #'linsubfct_distr',
    #'reconstr_dataset',
    #'label_info',
    #'mse_test',
    #    'linSub_unifPoints',
    #    'subfunc_distmat',
    #    'linsubfct_parallelPlots',
    #'singularValuePlots',
    #'closest_linsubfct_plot',
    #'boundary_2d_plot',
    #'inst_area_2d_plot',
    #'border_dist_2d',
    #'border_dist_sort_plot',
    #'error_border_dist_plot',
    #'orig_latent_dist_ratios',
    #'error_label_mean_dist_plot',
    #'error_border_dist_plot_colored',
    #'error_border_dist_plot_anomalies',
    #'plot_mnist_samples',
    #'image_lrp',
    #'image_feature_imp',
    #'qual_by_border_dist_plot',
    #'fct_change_by_border_dist_qual',
    #'marabou_classes',
    'marabou_robust',
    #'marabou_anomalous',
    #'marabou_largest_error',
    #'bias_feature_imp',
    #'interpolation_func_diffs_pairs',
    #'interpolation_error_plot',
    #'mnist_interpolation_func_diffs_pairs',
]

datasets:
    subsample:                      Null
    synthetic_test_samples:         100
    gaussianClouds:
        #file_path:                  './datasets/synthetic/gaussianClouds/60'
        file_path:                  './models/trained_models/autoencoder/dataset/gaussianClouds'
        #file_path:                  Null
        num_clouds:                 3
        num_samples:                1000
        num_anomalies:              0
        spacedim:                   60
        clouddim:                   4
    uniformClouds:
        #file_path:                  Null
        file_path:                  './datasets/synthetic/uniformClouds/60'
        num_clouds:                 3
        num_samples:                1000
        num_anomalies:              0
        spacedim:                   60
        clouddim:                   4
        noise:                      False
    sineNoise:
        file_path:                  './datasets/synthetic/sineNoise/60'
        #file_path:                  Null
        num_samples:                1000
        num_anomalies:              0
        spacedim:                   60
    moons_2d:
        #file_path:                  Null
        file_path:                  './datasets/synthetic/moons_2d'
        num_samples:                2000
        num_anomalies:              10
        noise:                      0.1
    parabola:
        #file_path:                  Null
        file_path:                  './datasets/synthetic/parabola'
        num_samples:                2000
        num_anomalies:              10
        noise:                      0.1
        spacedim:                   2
    mnist:
        file_path:                  Null
        num_samples:                35000
        num_anomalies:              0
    predictiveMaintenance:
        file_path:                  Null
        num_samples:                -1
        num_anomalies:              0
        window_size:                50
    creditcardFraud:
        file_path:                  Null
        num_samples:                -1
        num_anomalies:              0
    electricDevices:
        file_path:                  './models/trained_models/autoencoder/dataset/electricDevices'
        #file_path:                  Null
    italyPowerDemand:
        file_path:                  './models/trained_models/autoencoder/dataset/italyPowerDemand'
        #file_path:                  Null
    ecg5000:
        file_path:                  './models/trained_models/autoencoder/dataset/ecg5000'
    proximalPhalanxOutlineCorrect:
        file_path:                  Null
    sonyAIBORobotSurface1:
        file_path:                  Null
    sonyAIBORobotSurface2:
        file_path:                  Null
    syntheticControl:
        file_path:                  Null
    twoLeadEcg:
        file_path:                  Null
    chinatown:
        file_path:                  Null
    crop:
        file_path:                  Null
        class1:                     5
        class2:                     15
    moteStrain:
        file_path:                  Null
    melbournePedestrian:
        file_path:                  Null
    wafer:
        file_path:                  Null
    chlorineConcentration:
        file_path:                  Null
    insectWbs:
        file_path:                  Null

algorithms:
    num_epochs:                     50
    dynamic_epochs:                 True
    lr:                             1e-3
    collect_subfcts:                False
    autoencoder:
        border_dist:                False
        fct_dist:                   True
        lambda_border:              0.005
        lambda_fct:                 0.05
        #topology:                   [2,5,5,5,2]
        topology:                   [784,350,150,50,10,50,150,350,784]
            # for mnist
            #topology:                   [29,10,3,10,29]
            # for creditcard_fraud
            #topology:                   [50,15,3,15,50]
            # for predMaintenance
            #topology:                   [1000,500,250,100,30,20,10,20,30,100, 250,500,1000]
            #topology:                   [60,30,15,30,60]
        #topology:                   [30,15,10,15,30]
        bias:                       True
        dropout:                    False
        num_border_points:          1
