repeat_experiment:                  1
ctx:                                'test'
mode:                               ['test']
test_models:                        './models/trained_models/reprod/dsaa/ae_sinecurve'
dataset:                            Null
algorithm:                          Null
evaluations:                        [
    'marabou_ens_normal_rob',
    'marabou_ens_normal_rob_ae',
    'marabou_svdd_normal_rob',
    'downstream_naiveBayes',
    'downstream_knn',
    'downstream_rf',
    'inst_area_2d_plot',
    'marabou_robust',
    'marabou_largest_error',
]
